spring.application.name=MVC03MiniProject



spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE

spring.datasource.username=C##HARSH
spring.datasource.password=harsh

#jpa configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#view resolver config
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp


#context path config
server.servlet.context-path=/MiniProjApp

server.port=8080

